name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build Samples with Java
      run: |
        cd Sample
        ./gradlew :java-sample:assembleDebug
    
    - name: Build Samples with Kotlin
      run: |
        cd Sample
        ./gradlew :kotlin-sample:assembleDebug
